name: CI

on:
  push:
    branches:
      - main
    paths:
      - '/*'  # This triggers the workflow for any file in the root directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Your Code
        uses: actions/checkout@v2

      - name: Say Hello to the World
        run: echo "Hello, World!"
