name: Auto Merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR
        run: |
          if [ "${{ github.event.pull_request.mergeable }}" == "true" ]; then
            echo "Merging PR #${{ github.event.pull_request.number }}"
            gh pr merge ${{ github.event.pull_request.number }} --merge
          else
            echo "PR #${{ github.event.pull_request.number }} is not mergeable."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
