name: Check Root Files And Auto-Merge

on:
  pull_request:
    paths:
      - '**/*'  # Run this on any changes made to the repository

jobs:
  check_deletions_and_root_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request if No Issues
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}  # Correct input
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN for authentication
          merge-method: MERGE  # You can specify MERGE, SQUASH, or REBASE
